allowBuilds:
    "@parcel/watcher": true
    "@swc/core": true
    sharp: true
    unrs-resolver: true
ignoredBuiltDependencies:
    - "@clerk/shared"

overrides:
    "@types/react": "19.2.17"
    "@types/react-dom": "19.2.3"
