import type { Metadata } from "next";
import { Roboto, Montserrat } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
    weight: ["400", "700"], // ajoutez les weights dont vous avez besoin
    subsets: ["latin"],
    variable: "--font-roboto",
});

const montserrat = Montserrat({
    weight: ["400", "500", "600", "700"],
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body className={`${montserrat.variable} ${roboto.variable} font-sans antialiased`}>{children}</body>
        </html>
    );
}
