name: Deploy Next on pre-prod

on:
    push:
        branches:
            - preprod
    pull_request:
        branches:
            - preprod
    workflow_dispatch:

jobs:
    deploy:
        runs-on: [self-hosted, linux, X64, VPS]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: deploy
              run: |
                  cd ~/projects/flepourtous
                  git checkout preprod
                  git pull origin preprod
                  cd backend
                  composer install --no-dev --optimize-autoloader
                  cd ..
                  cd frontend
                  pnpm i
                  pm2 stop flepourtous-preprod
                  pnpm run build
                  pm2 start flepourtous-preprod
