name: Deploy Next on pre-prod

on:
    pull_request:
        branches:
            - preprod
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PSW }}
                  script: |
                      cd ~/projects/flepourtous
                      git restore .
                      git checkout preprod
                      git pull origin preprod
                      cd backend
                      composer install --no-dev --optimize-autoloader
                      cd ..
                      cd frontend
                      pnpm i
                      pm2 stop flepourtous-preprod
                      rm -rf .next
                      pnpm run build
                      pm2 start flepourtous-preprod
