name: Deploy Next on pre-prod

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev
    workflow_dispatch:

jobs:
    deploy:
        runs-on: [self-hosted, linux, X64, VPS]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: deploy
              run: |
                  cd ~/projects/flepourtous
                  git restore .
                  git checkout dev
                  git pull origin dev
                  cd frontend
                  pnpm i
                  pm2 stop flepourtous-preprod
                  pnpm run build
                  pm2 start flepourtous-preprod
