name: Deploy Next on pre-prod

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: [self-hosted, linux, X64, VPS]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: deploy
              run: |
                  cd ~/projects/prod/flepourtous-prod
                  git checkout main
                  git pull origin main
                  cd frontend
                  pnpm i
                  pnpm build
                  pm2 restart flepourtous-prod
